train-script: "run_train1.sh"
agg-script: "run_aggregation.sh"
infer-script: "run_forward1.sh"
rounds: "12"
initial-round: "10"
job-prefix: "model-241116-2"
split_csv: "cc359ppmi128/CC359PPMI_nj4r12v3.csv"
init_model: "/fedpod/states/nj6r12v3_0/R12r10/models/R12r10_agg.pth"