apiVersion: v1
kind: Pod
metadata:
  name: fedpod-cuda
spec:
spec:
  restartPolicy: Never
  containers:
  - name: fedpod-container
    image: dwnusa/fedpod:v0.4.0-cuda # Docker 이미지
    command: ["/bin/bash", "-c"]  # 쉘 명령으로 실행
    args: ["./run_train.sh -j inst_all -R 0 -r 0 -E 20 -i 1,2,3,4,5,6"]
    volumeMounts:
    - name: cc359ppmi128-volume
      mountPath: /fedpod/cc359ppmi128
    - name: states-volume
      mountPath: /fedpod/states
    stdin: true
    tty: true
  volumes:
  - name: cc359ppmi128-volume
    hostPath:
      path: /fedpod/cc359ppmi128  # 로컬 경로
      type: Directory
  - name: states-volume
    hostPath:
      path: /fedpod/states  # 로컬 경로
      type: Directory
