apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fedpod-
spec:
  entrypoint: infer-dag
  # onExit: infer-dag
  arguments:
    parameters:
    - name: rounds
      value: "20"
    - name: selected-round
      value: "20"
    - name: selected-epoch
      value: "00"

    - name: data_root
      value: "data_cc359ppmicmc256_dwnusa"
    - name: infer-script
      value: "run_forward2.sh"
    - name: forward-script
      value: "run_forward.sh"
    - name: input_channel_names
      value: "None"
    - name: job-prefix
      value: "undefined"
    - name: split_csv
      value: "undefined"

    - name: model_pth
      value: "None"
      
  templates:
  - name: infer-dag
    dag:
      tasks:
      - name: infer-2
        template: infer-job
        arguments:
          parameters:
          - name: run-script
            value: "{{workflow.parameters.forward-script}}"
          - name: job-name
            value: "{{workflow.parameters.job-prefix}}_{{item.inst}}_forward"
          - name: rounds
            value: "{{item.rounds}}"
          - name: round
            value: "{{item.round}}"
          - name: epoch
            value: "{{item.epoch}}"
          - name: inst-id
            value: "{{item.inst}}"
          - name: split_csv
            value: "{{item.split_csv}}"
          - name: model_pth
            value: "{{item.model_pth}}"
          - name: data_root
            value: "{{workflow.parameters.data_root}}"
          - name: data_set
            value: "{{workflow.parameters.data_set}}"
          - name: inst_root
            value: "inst_00"
          - name: input_channels
            value: "{{workflow.parameters.input_channel_names}}"
          - name: label_groups
            value: "{{workflow.parameters.label_groups}}"
          - name: label_names
            value: "{{workflow.parameters.label_names}}"
          - name: label_index
            value: "{{workflow.parameters.label_index}}"
          - name: seg_postfix
            value: "{{workflow.parameters.seg_postfix}}"
          - name: sel_list
            value: "[train]"
        withItems:
        - { rounds: "{{workflow.parameters.rounds}}",
            round: "20", 
            epoch: "000", 
            inst: "0",
            split_csv: "{{workflow.parameters.split_csv}}",
            model_pth: "/fedpod/states/{{workflow.parameters.job-prefix}}_0/R20r20/models/R20r20_agg.pth" }

  - name: infer-job
    inputs:
      parameters:
      - name: run-script
      - name: job-name
      - name: rounds
      - name: round
      - name: epoch
      - name: inst-id
      - name: split_csv
      - name: model_pth
      - name: data_root
      - name: data_set
      - name: inst_root
      - name: input_channels
      - name: label_groups
      - name: label_names
      - name: label_index
      - name: seg_postfix
      - name: sel_list
    container:
      image: dwnusa/fedpod:v0.4.18.15
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      args: 
        - >
          ./{{inputs.parameters.run-script}}
          -s 1
          -g 0
          -J {{inputs.parameters.job-name}}
          -i {{inputs.parameters.inst-id}}
          -R {{inputs.parameters.rounds}}
          -r {{inputs.parameters.round}}
          -e {{inputs.parameters.epoch}}
          -c {{inputs.parameters.split_csv}}
          -M {{inputs.parameters.model_pth}}
          -t {{inputs.parameters.sel_list}}
          -D {{inputs.parameters.data_root}}
          -d {{inputs.parameters.data_set}}
          -n {{inputs.parameters.inst_root}}
          -C {{inputs.parameters.input_channels}}
          -G {{inputs.parameters.label_groups}}
          -N {{inputs.parameters.label_names}}
          -I {{inputs.parameters.label_index}}
          -p {{inputs.parameters.seg_postfix}}
      resources:
        requests:
          cpu: "2"
          memory: "8G"
      volumeMounts:
      - name: csv-volume
        mountPath: /fedpod/experiments
      - name: cc359ppmi128-volume
        mountPath: /fedpod/data
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      - name: runs-volume
        mountPath: /fedpod/runs
      stdin: true
      tty: true
    volumes:
    - name: csv-volume
      hostPath:
        path: /fedpod/experiments  # 로컬 경로
        type: Directory
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/{{inputs.parameters.data_root}}  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory
    - name: runs-volume
      hostPath:
        path: /fedpod/runs  # 로컬 경로
        type: Directory
