apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parallel-jobs-
spec:
  entrypoint: parallel-steps
  arguments:
    parameters:
    - name: rounds
      value: "05"
    - name: job-prefix
      value: "inst"
    - name: split_csv
      value: "cc359ppmi128/CC359PPMI_v1-test.csv"
  templates:
  - name: parallel-steps
    steps:
  # round 0
    - - name: run-aggregation-jobs-00
        template: aggregation-job
        arguments:
          parameters:
          - name: round
            value: "0"
          - name: algorithm
            value: "fedavg"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/cc359ppmi128/R00E000.pth"
        withItems:
        - { inst: "0" }
    - - name: run-train-jobs-00
        template: train-job
        arguments:
          parameters:
          - name: round
            value: "0"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/states/R{{workflow.parameters.rounds}}r00/{{workflow.parameters.job-prefix}}0/R{{workflow.parameters.rounds}}r00.pth"
        withItems:
        - { inst: "1" }
        - { inst: "2" }
        - { inst: "3" }
        - { inst: "4" }
        - { inst: "5" }
        - { inst: "6" }
  # round 1
    - - name: run-aggregation-jobs-01
        template: aggregation-job
        arguments:
          parameters:
          - name: round
            value: "1"
          - name: algorithm
            value: "fedavg"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "None"
        withItems:
        - { inst: "0" }
    - - name: run-train-jobs-01
        template: train-job
        arguments:
          parameters:
          - name: round
            value: "1"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/states/R{{workflow.parameters.rounds}}r01/{{workflow.parameters.job-prefix}}0/R{{workflow.parameters.rounds}}r01.pth"
        withItems:
        - { inst: "1" }
        - { inst: "2" }
        - { inst: "3" }
        - { inst: "4" }
        - { inst: "5" }
        - { inst: "6" }
  # round 2
    - - name: run-aggregation-jobs-02
        template: aggregation-job
        arguments:
          parameters:
          - name: round
            value: "2"
          - name: algorithm
            value: "fedavg"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "None"
        withItems:
        - { inst: "0" }
    - - name: run-train-jobs-02
        template: train-job
        arguments:
          parameters:
          - name: round
            value: "2"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/states/R{{workflow.parameters.rounds}}r02/{{workflow.parameters.job-prefix}}0/R{{workflow.parameters.rounds}}r02.pth"
        withItems:
        - { inst: "1" }
        - { inst: "2" }
        - { inst: "3" }
        - { inst: "4" }
        - { inst: "5" }
        - { inst: "6" }
  # round 3
    - - name: run-aggregation-jobs-03
        template: aggregation-job
        arguments:
          parameters:
          - name: round
            value: "3"
          - name: algorithm
            value: "fedavg"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "None"
        withItems:
        - { inst: "0" }
    - - name: run-train-jobs-03
        template: train-job
        arguments:
          parameters:
          - name: round
            value: "3"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/states/R{{workflow.parameters.rounds}}r03/{{workflow.parameters.job-prefix}}0/R{{workflow.parameters.rounds}}r03.pth"
        withItems:
        - { inst: "1" }
        - { inst: "2" }
        - { inst: "3" }
        - { inst: "4" }
        - { inst: "5" }
        - { inst: "6" }
  # round 4
    - - name: run-aggregation-jobs-04
        template: aggregation-job
        arguments:
          parameters:
          - name: round
            value: "4"
          - name: algorithm
            value: "fedavg"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "None"
        withItems:
        - { inst: "0" }
    - - name: run-train-jobs-04
        template: train-job
        arguments:
          parameters:
          - name: round
            value: "4"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/states/R{{workflow.parameters.rounds}}r04/{{workflow.parameters.job-prefix}}0/R{{workflow.parameters.rounds}}r04.pth"
        withItems:
        - { inst: "1" }
        - { inst: "2" }
        - { inst: "3" }
        - { inst: "4" }
        - { inst: "5" }
        - { inst: "6" }





  - name: train-job
    inputs:
      parameters:
      - name: round
      - name: inst-id
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.12
      command: ["/bin/sh", "-c"]
      args: ["./run_train.sh -s 0 -g 0 -j {{workflow.parameters.job-prefix}}{{inputs.parameters.inst-id}} -R {{workflow.parameters.rounds}} -r {{inputs.parameters.round}} -E 1 -i {{inputs.parameters.inst-id}} -c {{workflow.parameters.split_csv}} -m {{inputs.parameters.model_pth}}"]
      resources:
        requests:
          cpu: "4"
          memory: "32G"
        limits:
          cpu: "6"
          memory: "64G"
      volumeMounts:
      - name: cc359ppmi128-volume
        mountPath: /fedpod/cc359ppmi128
      - name: states-volume
        mountPath: /fedpod/states
      stdin: true
      tty: true
    volumes:
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/cc359ppmi128  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory

  - name: aggregation-job
    inputs:
      parameters:
      - name: round
      - name: algorithm
      - name: inst-id
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.12
      command: ["/bin/sh", "-c"]
      args: ["./run_aggregation.sh -R {{workflow.parameters.rounds}} -r {{inputs.parameters.round}} -a {{inputs.parameters.algorithm}} -j {{workflow.parameters.job-prefix}} -i {{inputs.parameters.inst-id}} -m {{inputs.parameters.model_pth}}"]
      # args: ["./run_aggregation.sh -r 0 -R 5 -a fedavg -j inst -i 0 -m /fedpod/cc359ppmi128/R00E000.pth"]
      resources:
        requests:
          cpu: "2"
          memory: "4G"
        limits:
          cpu: "6"
          memory: "8G"
      volumeMounts:
      - name: cc359ppmi128-volume
        mountPath: /fedpod/cc359ppmi128
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      stdin: true
      tty: true
    volumes:
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/cc359ppmi128  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory

