apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fedpod-jobs-
spec:
  entrypoint: parallel-steps
  # arguments:
    # parameters:
    # - name: split_csv
    #   value: "cc359ppmi128/CC359PPMI_v1-test.csv"
  templates:
  - name: parallel-steps
    steps:
  # infer using local models
    - - name: run-infer-jobs-00
        template: infer-job
        arguments:
          parameters:
          - name: script-name
            value: "run_infer1.sh"
          - name: job-name
            value: "{{item.job-name}}"
          - name: rounds
            value: "{{item.rounds}}"
          - name: round
            value: "{{item.round}}"
          - name: epoch
            value: "{{item.epoch}}"
          - name: inst-id
            value: "{{item.inst}}"
          - name: split_csv
            value: "{{item.split_csv}}"
          - name: model_pth
            value: "{{item.model_pth}}"
        withItems:
        - { job-name: "best_cen1_1", rounds: "04", round: "01", epoch: "000", inst: "1", split_csv: "cc359ppmi128/CC359PPMI_v1-test.csv", model_pth: "/fedpod/states/solo_2/R01r01/models/R01r01_best.pth"}
        - { job-name: "best_cen1_2", rounds: "04", round: "01", epoch: "000", inst: "2", split_csv: "cc359ppmi128/CC359PPMI_v1-test.csv", model_pth: "/fedpod/states/solo_2/R01r01/models/R01r01_best.pth"}
        - { job-name: "best_cen1_3", rounds: "04", round: "01", epoch: "000", inst: "3", split_csv: "cc359ppmi128/CC359PPMI_v1-test.csv", model_pth: "/fedpod/states/solo_2/R01r01/models/R01r01_best.pth"}
        - { job-name: "best_cen1_4", rounds: "04", round: "01", epoch: "000", inst: "4", split_csv: "cc359ppmi128/CC359PPMI_v1-test.csv", model_pth: "/fedpod/states/solo_2/R01r01/models/R01r01_best.pth"}
        - { job-name: "best_cen1_5", rounds: "04", round: "01", epoch: "000", inst: "5", split_csv: "cc359ppmi128/CC359PPMI_v1-test.csv", model_pth: "/fedpod/states/solo_2/R01r01/models/R01r01_best.pth"}
        - { job-name: "best_cen1_6", rounds: "04", round: "01", epoch: "000", inst: "6", split_csv: "cc359ppmi128/CC359PPMI_v1-test.csv", model_pth: "/fedpod/states/solo_2/R01r01/models/R01r01_best.pth"}

    - - name: run-infer-jobs-01
        template: infer-job
        arguments:
          parameters:
          - name: script-name
            value: "run_infer1.sh"
          - name: job-name
            value: "{{item.job-name}}"
          - name: rounds
            value: "{{item.rounds}}"
          - name: round
            value: "{{item.round}}"
          - name: epoch
            value: "{{item.epoch}}"
          - name: inst-id
            value: "{{item.inst}}"
          - name: split_csv
            value: "{{item.split_csv}}"
          - name: model_pth
            value: "{{item.model_pth}}"
        withItems:
        - { job-name: "test_cen_0", rounds: "04", round: "01", epoch: "000", inst: "1", split_csv: "cc359ppmi128/CC359PPMI_v1-test.csv", model_pth: "/fedpod/states/cen_0/R00r01/models/R00r01.pth"}
        - { job-name: "test_cen_0", rounds: "04", round: "01", epoch: "000", inst: "2", split_csv: "cc359ppmi128/CC359PPMI_v1-test.csv", model_pth: "/fedpod/states/cen_0/R00r01/models/R00r01.pth"}
        - { job-name: "test_cen_0", rounds: "04", round: "01", epoch: "000", inst: "3", split_csv: "cc359ppmi128/CC359PPMI_v1-test.csv", model_pth: "/fedpod/states/cen_0/R00r01/models/R00r01.pth"}
        - { job-name: "test_cen_0", rounds: "04", round: "01", epoch: "000", inst: "4", split_csv: "cc359ppmi128/CC359PPMI_v1-test.csv", model_pth: "/fedpod/states/cen_0/R00r01/models/R00r01.pth"}
        - { job-name: "test_cen_0", rounds: "04", round: "01", epoch: "000", inst: "5", split_csv: "cc359ppmi128/CC359PPMI_v1-test.csv", model_pth: "/fedpod/states/cen_0/R00r01/models/R00r01.pth"}
        - { job-name: "test_cen_0", rounds: "04", round: "01", epoch: "000", inst: "6", split_csv: "cc359ppmi128/CC359PPMI_v1-test.csv", model_pth: "/fedpod/states/cen_0/R00r01/models/R00r01.pth"}

  - name: infer-job
    inputs:
      parameters:
      - name: script-name
      - name: job-name
      - name: rounds
      - name: round
      - name: epoch
      - name: inst-id
      - name: split_csv
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.14.21
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      args: 
        - >
          ./{{inputs.parameters.script-name}}
          -s 1
          -g 0
          -J {{inputs.parameters.job-name}}
          -i {{inputs.parameters.inst-id}}
          -R {{inputs.parameters.rounds}}
          -r {{inputs.parameters.round}}
          -e {{inputs.parameters.epoch}}
          -c {{inputs.parameters.split_csv}}
          -m {{inputs.parameters.model_pth}}
      resources:
        requests:
          cpu: "2"
          memory: "16G"
      volumeMounts:
      - name: cc359ppmi128-volume
        mountPath: /fedpod/cc359ppmi128
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      stdin: true
      tty: true
    volumes:
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/cc359ppmi128  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory
