apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fedpod-jobs-
spec:
  entrypoint: parallel-steps
  arguments:
    parameters:
    - name: rounds
      value: "01" # mode selection role: (cen: 00, solo: 01, fed: >= 02)
    - name: initial-round
      value: "00"
    - name: job-prefix
      value: "solo"
    - name: split_csv
      value: "cc359ppmi128/CC359PPMI_v1-test.csv"
  
  templates:
  - name: parallel-steps
    dag:  # steps 대신 dag 템플릿 사용
      tasks:
      # inst 1
      - name: run-train-job-1
        template: train-job
        arguments:
          parameters:
          - name: script-name
            value: "run_train1.sh"
          - name: round
            value: "{{workflow.parameters.initial-round}}"
          - name: epochs
            value: "020"
          - name: epoch
            value: "000"
          - name: inst-id
            value: "3"
          - name: model_pth
            value: "None"
      
      - name: run-aggregation-job-1
        dependencies: [run-train-job-1]  # inst-id 1에 대한 의존성 설정
        template: aggregation-job
        arguments:
          parameters:
          - name: script-name
            value: "run_aggregation.sh"
          - name: round
            value: "00"
          - name: epochs
            value: "020"
          - name: epoch
            value: "000"
          - name: algorithm
            value: "fedavg"
          - name: inst-id
            value: "3"
          - name: model_pth
            value: "None"

      # inst 2
      - name: run-train-job-2
        template: train-job
        arguments:
          parameters:
          - name: script-name
            value: "run_train1.sh"
          - name: round
            value: "00"
          - name: epochs
            value: "020"
          - name: epoch
            value: "000"
          - name: inst-id
            value: "2"
          - name: model_pth
            value: "None"

      - name: run-aggregation-job-2
        dependencies: [run-train-job-2]  # inst-id 2에 대한 의존성 설정
        template: aggregation-job
        arguments:
          parameters:
          - name: script-name
            value: "run_aggregation.sh"
          - name: round
            value: "00"
          - name: epochs
            value: "020"
          - name: epoch
            value: "000"
          - name: inst-id
            value: "2"
          - name: model_pth
            value: "None"
          - name: algorithm
            value: "fedavg"



  - name: train-job
    inputs:
      parameters:
      - name: script-name
      - name: round
      - name: epochs
      - name: epoch

      - name: inst-id
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.14.21
      command: ["/bin/sh", "-c"]
      args:
        - >
          ./{{inputs.parameters.script-name}} 
          -s 1 
          -g 0 

          -J {{workflow.parameters.job-prefix}}_{{inputs.parameters.inst-id}} 
          -R {{workflow.parameters.rounds}} 
          -r {{inputs.parameters.round}} 
          -E {{inputs.parameters.epochs}} 
          -e {{inputs.parameters.epoch}} 

          -i {{inputs.parameters.inst-id}} 
          -c {{workflow.parameters.split_csv}} 
          -m {{inputs.parameters.model_pth}}
      resources:
        requests:
          cpu: "2"
          memory: "16G"
      volumeMounts:
      - name: cc359ppmi128-volume
        mountPath: /fedpod/cc359ppmi128
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      stdin: true
      tty: true
    volumes:
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/cc359ppmi128  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory


  - name: aggregation-job
    inputs:
      parameters:
      - name: script-name
      - name: round
      - name: epochs
      - name: epoch
      - name: algorithm
      - name: inst-id
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.14.21
      command: ["/bin/sh", "-c"]
      args:
        - >
          ./{{inputs.parameters.script-name}} 
          -R {{workflow.parameters.rounds}} 
          -r {{inputs.parameters.round}} 
          -E {{inputs.parameters.epochs}} 
          -e {{inputs.parameters.epoch}} 
          
          -a {{inputs.parameters.algorithm}} 
          -j {{workflow.parameters.job-prefix}} 
          -i {{inputs.parameters.inst-id}} 
          -m {{inputs.parameters.model_pth}}
      resources:
        requests:
          cpu: "2"
          memory: "4G"
      volumeMounts:
      - name: cc359ppmi128-volume
        mountPath: /fedpod/cc359ppmi128
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      stdin: true
      tty: true
    outputs:
      parameters:
      - name: next-round
        valueFrom:
          path: /tmp/next_round.txt  # Return the value from the temp file
      - name: next-epoch
        valueFrom:
          path: /tmp/next_epoch.txt
    volumes:
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/cc359ppmi128  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory