apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fedpod-jobs-
spec:
  entrypoint: parallel-steps
  arguments:
    parameters:
    - name: rounds
      value: "05"
    - name: initial-round
      value: "00"
    - name: job-prefix
      value: "fed"
    - name: split_csv
      value: "cc359ppmi128/CC359PPMI128_fed-test.csv"
  templates:
  - name: parallel-steps
    steps:
  # round 0
    - - name: run-train-jobs-00
        template: train-job
        arguments:
          parameters:
          - name: script-name
            value: "run_train1.sh"
          - name: round
            value: "{{workflow.parameters.initial-round}}"
          - name: epochs
            value: "001"
          - name: epoch
            value: "000"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "None"
        withItems:
        # - { inst: "1" } # epochs: "001", epoch: "000", 
        # - { inst: "2" } # epochs: "001", epoch: "000", 
        - { inst: "3" } # epochs: "001", epoch: "000", 
        # - { inst: "4" } # epochs: "001", epoch: "000", 
        # - { inst: "5" } # epochs: "001", epoch: "000", 
        # - { inst: "6" } # epochs: "001", epoch: "000", 
    - - name: run-aggregation-jobs-00
        template: aggregation-job
        arguments:
          parameters:
          - name: script-name
            value: "run_aggregation.sh"
          - name: round
            value: "{{workflow.parameters.initial-round}}"
          - name: epochs
            value: "001" # "{{item.epochs}}"
          - name: epoch
            value: "000" # "{{item.epoch}}"
          - name: inst-id
            value: "0"
          - name: model_pth
            value: "None"
          - name: algorithm
            value: "fedavg"
  # round 1
    - - name: run-train-jobs-01
        template: train-job
        arguments:
          parameters:
          - name: script-name
            value: "run_train1.sh"
          - name: round
            value: "{{steps.run-aggregation-jobs-00.outputs.parameters.next-round}}"
          - name: epochs
            value: "001"
          - name: epoch
            value: "{{steps.run-aggregation-jobs-00.outputs.parameters.next-round}}"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/states/{{workflow.parameters.job-prefix}}_0/R{{workflow.parameters.rounds}}r{{steps.run-aggregation-jobs-00.outputs.parameters.next-round}}/models/R{{workflow.parameters.rounds}}r{{steps.run-aggregation-jobs-00.outputs.parameters.next-round}}_agg.pth"
        withItems:
        # - { inst: "1" } # epochs: "001", epoch: "001", 
        # - { inst: "2" } # epochs: "001", epoch: "001", 
        - { inst: "3" } # epochs: "001", epoch: "001", 
        - { inst: "4" } # epochs: "001", epoch: "001", 
        - { inst: "5" } # epochs: "001", epoch: "001", 
        - { inst: "6" } # epochs: "001", epoch: "001", 
    - - name: run-aggregation-jobs-01
        template: aggregation-job
        arguments:
          parameters:
          - name: script-name
            value: "run_aggregation.sh"
          - name: round
            value: "{{steps.run-aggregation-jobs-00.outputs.parameters.next-round}}"
          - name: epochs
            value: "001"
          - name: epoch
            value: "{{steps.run-aggregation-jobs-00.outputs.parameters.next-round}}"
          - name: inst-id
            value: "0"
          - name: model_pth
            value: "None"
          - name: algorithm
            value: "fedavg"
  # round 2
    - - name: run-train-jobs-02
        template: train-job
        arguments:
          parameters:
          - name: script-name
            value: "run_train1.sh"
          - name: round
            value: "{{steps.run-aggregation-jobs-01.outputs.parameters.next-round}}"
          - name: epochs
            value: "001"
          - name: epoch
            value: "{{steps.run-aggregation-jobs-01.outputs.parameters.next-round}}"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/states/{{workflow.parameters.job-prefix}}_0/R{{workflow.parameters.rounds}}r{{steps.run-aggregation-jobs-01.outputs.parameters.next-round}}/models/R{{workflow.parameters.rounds}}r{{steps.run-aggregation-jobs-01.outputs.parameters.next-round}}_agg.pth"
        withItems:
        # - { inst: "1" } # epochs: "001", epoch: "002", 
        - { inst: "2" } # epochs: "001", epoch: "002", 
        - { inst: "3" } # epochs: "001", epoch: "002", 
        - { inst: "4" } # epochs: "001", epoch: "002", 
        - { inst: "5" } # epochs: "001", epoch: "002", 
        - { inst: "6" } # epochs: "001", epoch: "002", 
    - - name: run-aggregation-jobs-02
        template: aggregation-job
        arguments:
          parameters:
          - name: script-name
            value: "run_aggregation.sh"
          - name: round
            value: "{{steps.run-aggregation-jobs-01.outputs.parameters.next-round}}"
          - name: epochs
            value: "001"
          - name: epoch
            value: "{{steps.run-aggregation-jobs-01.outputs.parameters.next-round}}"
          - name: inst-id
            value: "0"
          - name: model_pth
            value: "None"
          - name: algorithm
            value: "fedavg"
  # round 3
    - - name: run-train-jobs-03
        template: train-job
        arguments:
          parameters:
          - name: script-name
            value: "run_train1.sh"
          - name: round
            value: "{{steps.run-aggregation-jobs-02.outputs.parameters.next-round}}"
          - name: epochs
            value: "001"
          - name: epoch
            value: "{{steps.run-aggregation-jobs-02.outputs.parameters.next-round}}"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/states/{{workflow.parameters.job-prefix}}_0/R{{workflow.parameters.rounds}}r{{steps.run-aggregation-jobs-02.outputs.parameters.next-round}}/models/R{{workflow.parameters.rounds}}r{{steps.run-aggregation-jobs-02.outputs.parameters.next-round}}_agg.pth"
        withItems:
        - { inst: "1" } # epochs: "001", epoch: "002", 
        - { inst: "2" } # epochs: "001", epoch: "002", 
        - { inst: "3" } # epochs: "001", epoch: "002", 
        - { inst: "4" } # epochs: "001", epoch: "002", 
        - { inst: "5" } # epochs: "001", epoch: "002", 
        - { inst: "6" } # epochs: "001", epoch: "002", 
    - - name: run-aggregation-jobs-03
        template: aggregation-job
        arguments:
          parameters:
          - name: script-name
            value: "run_aggregation.sh"
          - name: round
            value: "{{steps.run-aggregation-jobs-02.outputs.parameters.next-round}}"
          - name: epochs
            value: "001" 
          - name: epoch
            value: "{{steps.run-aggregation-jobs-02.outputs.parameters.next-round}}"
          - name: inst-id
            value: "0"
          - name: model_pth
            value: "None"
          - name: algorithm
            value: "fedavg"
  # round 4
    - - name: run-train-jobs-04
        template: train-job
        arguments:
          parameters:
          - name: script-name
            value: "run_train1.sh"
          - name: round
            value: "{{steps.run-aggregation-jobs-03.outputs.parameters.next-round}}"
          - name: epochs
            value: "001"
          - name: epoch
            value: "{{steps.run-aggregation-jobs-03.outputs.parameters.next-round}}" 
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/states/{{workflow.parameters.job-prefix}}_0/R{{workflow.parameters.rounds}}r{{steps.run-aggregation-jobs-03.outputs.parameters.next-round}}/models/R{{workflow.parameters.rounds}}r{{steps.run-aggregation-jobs-03.outputs.parameters.next-round}}_agg.pth"
        withItems:
        - { inst: "1" } # epochs: "001", epoch: "002", 
        - { inst: "2" } # epochs: "001", epoch: "002", 
        - { inst: "3" } # epochs: "001", epoch: "002", 
        - { inst: "4" } # epochs: "001", epoch: "002", 
        - { inst: "5" } # epochs: "001", epoch: "002", 
        - { inst: "6" } # epochs: "001", epoch: "002", 
    - - name: run-aggregation-jobs-04
        template: aggregation-job
        arguments:
          parameters:
          - name: script-name
            value: "run_aggregation.sh"
          - name: round
            value: "{{steps.run-aggregation-jobs-03.outputs.parameters.next-round}}"
          - name: epochs
            value: "001" 
          - name: epoch
            value: "{{steps.run-aggregation-jobs-03.outputs.parameters.next-round}}" 
          - name: inst-id
            value: "0"
          - name: model_pth
            value: "None"
          - name: algorithm
            value: "fedavg"

    - - name: run-infer-jobs-04
        template: infer-job
        arguments:
          parameters:
          - name: script-name
            value: "run_infer1.sh"
          - name: job-name
            value: "{{item.job-name}}"
          - name: rounds
            value: "{{item.rounds}}"
          - name: round
            value: "{{item.round}}"
          - name: epoch
            value: "{{item.epoch}}"
          - name: inst-id
            value: "{{item.inst}}"
          - name: split_csv
            value: "{{item.split_csv}}"
          - name: model_pth
            value: "{{item.model_pth}}"
        withItems:
        - { job-name: "fed_1_val", rounds: "05", round: "05", epoch: "005", inst: "1", split_csv: "cc359ppmi128/CC359PPMI128_fed-test.csv", model_pth: "/fedpod/states/fed_0/R04r04/models/R04r04.pth"}
        - { job-name: "fed_2_val", rounds: "05", round: "05", epoch: "005", inst: "2", split_csv: "cc359ppmi128/CC359PPMI128_fed-test.csv", model_pth: "/fedpod/states/fed_0/R04r04/models/R04r04.pth"}
        - { job-name: "fed_3_val", rounds: "05", round: "05", epoch: "005", inst: "3", split_csv: "cc359ppmi128/CC359PPMI128_fed-test.csv", model_pth: "/fedpod/states/fed_0/R04r04/models/R04r04.pth"}
        - { job-name: "fed_4_val", rounds: "05", round: "05", epoch: "005", inst: "4", split_csv: "cc359ppmi128/CC359PPMI128_fed-test.csv", model_pth: "/fedpod/states/fed_0/R04r04/models/R04r04.pth"}
        - { job-name: "fed_5_val", rounds: "05", round: "05", epoch: "005", inst: "5", split_csv: "cc359ppmi128/CC359PPMI128_fed-test.csv", model_pth: "/fedpod/states/fed_0/R04r04/models/R04r04.pth"}
        - { job-name: "fed_6_val", rounds: "05", round: "05", epoch: "005", inst: "6", split_csv: "cc359ppmi128/CC359PPMI128_fed-test.csv", model_pth: "/fedpod/states/fed_0/R04r04/models/R04r04.pth"}


  - name: train-job
    inputs:
      parameters:
      - name: script-name
      - name: round
      - name: epochs
      - name: epoch
      - name: inst-id
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.15.1
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      args:
        - >
          ./{{inputs.parameters.script-name}} 
          -s 0 
          -f 10
          -g 0 
          -J {{workflow.parameters.job-prefix}}_{{inputs.parameters.inst-id}} 
          -R {{workflow.parameters.rounds}} 
          -r {{inputs.parameters.round}} 
          -E {{inputs.parameters.epochs}} 
          -e {{inputs.parameters.epoch}} 
          -i {{inputs.parameters.inst-id}} 
          -c {{workflow.parameters.split_csv}} 
          -m {{inputs.parameters.model_pth}}
      resources:
        requests:
          cpu: "2"
          memory: "16G"
      volumeMounts:
      - name: cc359ppmi128-volume
        mountPath: /fedpod/cc359ppmi128
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      stdin: true
      tty: true
    volumes:
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/cc359ppmi128  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory


  - name: aggregation-job
    inputs:
      parameters:
      - name: script-name
      - name: round
      - name: epochs
      - name: epoch
      - name: algorithm
      - name: inst-id
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.15.1
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      args: 
        - >
          ./{{inputs.parameters.script-name}} 
          -R {{workflow.parameters.rounds}} 
          -r {{inputs.parameters.round}} 
          -E {{inputs.parameters.epochs}} 
          -e {{inputs.parameters.epoch}} 
          -j {{workflow.parameters.job-prefix}} 
          -i {{inputs.parameters.inst-id}} 
          -a {{inputs.parameters.algorithm}} 
          -m {{inputs.parameters.model_pth}}
      resources:
        requests:
          cpu: "2"
          memory: "4G"
      volumeMounts:
      - name: cc359ppmi128-volume
        mountPath: /fedpod/cc359ppmi128
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      stdin: true
      tty: true
    outputs:
      parameters:
      - name: next-round
        valueFrom:
          path: /tmp/next_round.txt  # Return the value from the temp file
      - name: next-epoch
        valueFrom:
          path: /tmp/next_epoch.txt
    volumes:
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/cc359ppmi128  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory

        
  - name: infer-job
    inputs:
      parameters:
      - name: script-name
      - name: job-name
      - name: rounds
      - name: round
      - name: epoch
      - name: inst-id
      - name: split_csv
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.15.1
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      args: 
        - >
          ./{{inputs.parameters.script-name}}
          -s 1
          -g 0
          -J {{inputs.parameters.job-name}}
          -i {{inputs.parameters.inst-id}}
          -R {{inputs.parameters.rounds}}
          -r {{inputs.parameters.round}}
          -e {{inputs.parameters.epoch}}
          -c {{inputs.parameters.split_csv}}
          -m {{inputs.parameters.model_pth}}
      resources:
        requests:
          cpu: "2"
          memory: "16G"
      volumeMounts:
      - name: cc359ppmi128-volume
        mountPath: /fedpod/cc359ppmi128
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      stdin: true
      tty: true
    volumes:
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/cc359ppmi128  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory