apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fedpod-jobs-
spec:
  entrypoint: parallel-steps-dag
  arguments:
    parameters:
    - name: rounds
      value: "03"
    - name: job-prefix
      value: "dag"
    - name: split_csv
      value: "cc359ppmi128/CC359PPMI_v1-test.csv"

  templates:
  - name: parallel-steps-dag
    dag:
      tasks:
      # Round 0 - Aggregation
      - name: run-aggregation-jobs-00
        template: aggregation-job
        arguments:
          parameters:
          - name: round
            value: "00"
          - name: algorithm
            value: "fedavg"
          - name: inst-id
            value: "0"
          - name: model_pth
            value: "None"

      # Round 0 - Training
      - name: run-train-jobs-00
        dependencies: [run-aggregation-jobs-00]
        template: train-job
        arguments:
          parameters:
          - name: round
            value: "00"
          - name: epochs
            value: "001"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "None"
        withItems:
        - { inst: "1" }
        - { inst: "2" }
        - { inst: "3" }
        - { inst: "4" }
        - { inst: "5" }
        - { inst: "6" }

      # Round 1 - Aggregation
      - name: run-aggregation-jobs-01
        dependencies: [run-train-jobs-00]
        template: aggregation-job
        arguments:
          parameters:
          - name: round
            value: "01"
          - name: algorithm
            value: "fedavg"
          - name: inst-id
            value: "0"
          - name: model_pth
            value: "None"

      # Round 1 - Training
      - name: run-train-jobs-01
        dependencies: [run-aggregation-jobs-01]
        template: train-job
        arguments:
          parameters:
          - name: round
            value: "01"
          - name: epochs
            value: "001"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/states/{{workflow.parameters.job-prefix}}_0/R{{workflow.parameters.rounds}}r01/models/R{{workflow.parameters.rounds}}r01.pth"
        withItems:
        - { inst: "1" }
        - { inst: "2" }
        - { inst: "3" }
        - { inst: "4" }
        - { inst: "5" }
        - { inst: "6" }

      # Round 2 - Aggregation
      - name: run-aggregation-jobs-02
        dependencies: [run-train-jobs-01]
        template: aggregation-job
        arguments:
          parameters:
          - name: round
            value: "02"
          - name: algorithm
            value: "fedavg"
          - name: inst-id
            value: "0"
          - name: model_pth
            value: "None"

      # Round 2 - Training
      - name: run-train-jobs-02
        dependencies: [run-aggregation-jobs-02]
        template: train-job
        arguments:
          parameters:
          - name: round
            value: "02"
          - name: epochs
            value: "001"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/states/{{workflow.parameters.job-prefix}}_0/R{{workflow.parameters.rounds}}r02/models/R{{workflow.parameters.rounds}}r02.pth"
        withItems:
        - { inst: "1" }
        - { inst: "2" }
        - { inst: "3" }
        - { inst: "4" }
        - { inst: "5" }
        - { inst: "6" }

      # Round 3 (End) - Aggregation
      - name: run-aggregation-jobs-03
        dependencies: [run-train-jobs-02]
        template: aggregation-job
        arguments:
          parameters:
          - name: round
            value: "03"
          - name: algorithm
            value: "fedavg"
          - name: inst-id
            value: "0"
          - name: model_pth
            value: "None"

  - name: aggregation-job
    inputs:
      parameters:
      - name: round
      - name: algorithm
      - name: inst-id
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.14.3
      command: ["/bin/sh", "-c"]
      args: ["./run_aggregation.sh -R {{workflow.parameters.rounds}} -r {{inputs.parameters.round}} -a {{inputs.parameters.algorithm}} -j {{workflow.parameters.job-prefix}} -i {{inputs.parameters.inst-id}} -m {{inputs.parameters.model_pth}}"]
      resources:
        requests:
          cpu: "2"
          memory: "4G"
      volumeMounts:
      - name: cc359ppmi128-volume
        mountPath: /fedpod/cc359ppmi128
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
    volumes:
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/cc359ppmi128
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs
        type: Directory

  - name: train-job
    inputs:
      parameters:
      - name: round
      - name: epochs
      - name: inst-id
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.14.3
      command: ["/bin/sh", "-c"]
      args: ["./run_train.sh -s 0 -g 0 -J {{workflow.parameters.job-prefix}}_{{inputs.parameters.inst-id}} -R {{workflow.parameters.rounds}} -r {{inputs.parameters.round}} -E {{inputs.parameters.epochs}} -i {{inputs.parameters.inst-id}} -c {{workflow.parameters.split_csv}} -m {{inputs.parameters.model_pth}}"]
      resources:
        requests:
          cpu: "2"
          memory: "64G"
      volumeMounts:
      - name: cc359ppmi128-volume
        mountPath: /fedpod/cc359ppmi128
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
    volumes:
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/cc359ppmi128
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs
        type: Directory
