apiVersion: v1
kind: Pod
metadata:
  name: fedpod-node01
spec:
  nodeName: node01
  restartPolicy: Never
  containers:
  - name: fedpod-container
    image: dwnusa/fedpod:v0.3.7  # Docker 이미지
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash", "-c"]  # 쉘 명령으로 실행
    args: ["./run_train.sh -j inst_01 -R 0 -r 0 -E 2 -i 1"]
    volumeMounts:
    - name: cc359ppmi128-volume
      mountPath: /fedpod/cc359ppmi128
    - name: states-volume
      mountPath: /fedpod/states
    stdin: true
    tty: true
  volumes:
  - name: cc359ppmi128-volume
    hostPath:
      path: /fedpod/cc359ppmi128  # 로컬 경로
      type: Directory
  - name: states-volume
    hostPath:
      path: /fedpod/states  # 로컬 경로
      type: Directory
---
apiVersion: v1
kind: Pod
metadata:
  name: fedpod-node02
spec:
  nodeName: node02
  restartPolicy: Never
  containers:
  - name: fedpod-container
    image: dwnusa/fedpod:v0.3.7  # Docker 이미지
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash", "-c"]  # 쉘 명령으로 실행
    args: ["./run_train.sh -j inst_02 -R 0 -r 0 -E 2 -i 2"]
    volumeMounts:
    - name: cc359ppmi128-volume
      mountPath: /fedpod/cc359ppmi128
    - name: states-volume
      mountPath: /fedpod/states
    stdin: true
    tty: true
  volumes:
  - name: cc359ppmi128-volume
    hostPath:
      path: /fedpod/cc359ppmi128  # 로컬 경로
      type: Directory
  - name: states-volume
    hostPath:
      path: /fedpod/states  # 로컬 경로
      type: Directory
