apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fedpod-jobs-
spec:
  entrypoint: parallel-steps
  arguments:
    parameters:
    - name: rounds
      value: "05"
    - name: job-prefix
      value: "inst"
    - name: split_csv
      value: "cc359ppmi128/CC359PPMI_v1.csv"
  templates:
  - name: parallel-steps
    steps:
    - - name: run-aggregation-jobs
        template: aggregation-job
        arguments:
          parameters:
          - name: round
            value: "{{item.round}}"
          - name: algorithm
            value: "fedavg"
          - name: inst-id
            value: "0"
          - name: model_pth
            value: "{{item.model_pth}}"
        withSequence:
          count: 5
          start: 0
        withItems:
        - { round: "0", model_pth: "/fedpod/cc359ppmi128/R00E000.pth" }
        - { round: "1", model_pth: "None" }
        - { round: "2", model_pth: "None" }
        - { round: "3", model_pth: "None" }
        - { round: "4", model_pth: "None" }
    - - name: run-train-jobs
        template: train-job
        arguments:
          parameters:
          - name: round
            value: "{{item.round}}"
          - name: inst-id
            value: "{{item.inst}}"
          - name: model_pth
            value: "/fedpod/states/R{{workflow.parameters.rounds}}r{{item.round}}/{{workflow.parameters.job-prefix}}0/models/R{{workflow.parameters.rounds}}r{{item.round}}.pth"
        withSequence:
          count: 5
          start: 0
        withItems:
        - { round: "0", inst: "1" }
        - { round: "0", inst: "2" }
        - { round: "0", inst: "3" }
        - { round: "0", inst: "4" }
        - { round: "0", inst: "5" }
        - { round: "0", inst: "6" }

        - { round: "1", inst: "1" }
        - { round: "1", inst: "2" }
        - { round: "1", inst: "3" }
        - { round: "1", inst: "4" }
        - { round: "1", inst: "5" }
        - { round: "1", inst: "6" }

        - { round: "2", inst: "1" }
        - { round: "2", inst: "2" }
        - { round: "2", inst: "3" }
        - { round: "2", inst: "4" }
        - { round: "2", inst: "5" }
        - { round: "2", inst: "6" }

        - { round: "3", inst: "1" }
        - { round: "3", inst: "2" }
        - { round: "3", inst: "3" }
        - { round: "3", inst: "4" }
        - { round: "3", inst: "5" }
        - { round: "3", inst: "6" }

        - { round: "4", inst: "1" }
        - { round: "4", inst: "2" }
        - { round: "4", inst: "3" }
        - { round: "4", inst: "4" }
        - { round: "4", inst: "5" }
        - { round: "4", inst: "6" }



  - name: train-job
    inputs:
      parameters:
      - name: round
      - name: inst-id
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.13.2
      command: ["/bin/sh", "-c"]
      args: ["./run_train.sh -s 0 -g 0 -j {{workflow.parameters.job-prefix}}{{inputs.parameters.inst-id}} -R {{workflow.parameters.rounds}} -r {{inputs.parameters.round}} -E 1 -i {{inputs.parameters.inst-id}} -c {{workflow.parameters.split_csv}} -m {{inputs.parameters.model_pth}}"]
      resources:
        requests:
          cpu: "4"
          memory: "32G"
        limits:
          cpu: "6"
          memory: "64G"
      volumeMounts:
      - name: cc359ppmi128-volume
        mountPath: /fedpod/cc359ppmi128
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      stdin: true
      tty: true
    volumes:
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/cc359ppmi128  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory

  - name: aggregation-job
    inputs:
      parameters:
      - name: round
      - name: algorithm
      - name: inst-id
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.13.2
      command: ["/bin/sh", "-c"]
      args: ["./run_aggregation.sh -R {{workflow.parameters.rounds}} -r {{inputs.parameters.round}} -a {{inputs.parameters.algorithm}} -j {{workflow.parameters.job-prefix}} -i {{inputs.parameters.inst-id}} -m {{inputs.parameters.model_pth}}"]
      # args: ["./run_aggregation.sh -r 0 -R 5 -a fedavg -j inst -i 0 -m /fedpod/cc359ppmi128/R00E000.pth"]
      resources:
        requests:
          cpu: "2"
          memory: "4G"
        limits:
          cpu: "6"
          memory: "8G"
      volumeMounts:
      - name: cc359ppmi128-volume
        mountPath: /fedpod/cc359ppmi128
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      stdin: true
      tty: true
    volumes:
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/cc359ppmi128  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory

