version: '3'
services:
  fedpod-test:
    image: dwnusa/fedpod:v0.4.16-test
    container_name: fedpod-test
    command: >
      /bin/bash -c "/fedpod/run_train1.sh 
      -s 0 
      -f 10
      -m 15
      -g 0 
      -J ${JOBNAME}
      -R ${ROUNDS}
      -r ${ROUND}
      -E 1
      -e 0
      -i ${INSTID}
      -c cc359ppmi128/CC359PPMI128_fed-test.csv
      -M None"
    stdin_open: true
    tty: true
    volumes:
      - /home2/jennyk0321/MASTER01/fedpod:/fedpod
      - /fedpod/cc359ppmi128:/fedpod/cc359ppmi128
      - /fedpod/states:/fedpod/states
      - /fedpod/logs:/fedpod/logs
      - /fedpod/runs:/fedpod/runs  # Absolute path on host mapped to /fedpod in container
