version: '3'
services:
  fedpod-test1:
    image: dwnusa/fedpod:v0.4.16-test
    container_name: fedpod-test1
    command: >
      /bin/bash -c "/fedpod/run_train1.sh 
      -s 0 
      -f 10
      -m 15
      -g 0 
      -J ${JOBNAME1}
      -R ${ROUNDS}
      -r ${ROUND}
      -E 1
      -e 0
      -i ${INSTID1}
      -c cc359ppmi128/CC359PPMI128_fed-test.csv
      -M ${MODEL}"
    stdin_open: true
    tty: true
    volumes:
      - /fedpod:/fedpod
      - /fedpod/cc359ppmi128:/fedpod/cc359ppmi128
      - /fedpod/states:/fedpod/states
      - /fedpod/logs:/fedpod/logs
      - /fedpod/runs:/fedpod/runs  # Absolute path on host mapped to /fedpod in container

  fedpod-test2:
    image: dwnusa/fedpod:v0.4.16-test
    container_name: fedpod-test2
    command: >
      /bin/bash -c "/fedpod/run_train1.sh 
      -s 0 
      -f 10
      -m 15
      -g 0 
      -J ${JOBNAME2}
      -R ${ROUNDS}
      -r ${ROUND}
      -E 1
      -e 0
      -i ${INSTID2}
      -c cc359ppmi128/CC359PPMI128_fed-test.csv
      -M ${MODEL}"
    stdin_open: true
    tty: true
    volumes:
      - /fedpod:/fedpod
      - /fedpod/cc359ppmi128:/fedpod/cc359ppmi128
      - /fedpod/states:/fedpod/states
      - /fedpod/logs:/fedpod/logs
      - /fedpod/runs:/fedpod/runs  # Absolute path on host mapped to /fedpod in container
