version: '3'
services:
  fedpod-test:
    image: dwnusa/fedpod:v0.4.16-test
    container_name: fedpod-test
    command: >
      /bin/bash -c "/fedpod/run_aggregation.sh 
      -R 5
      -r 0
      -E 1
      -e 0
      -j fed
      -i 0
      -a fedavg
      -M None"
    stdin_open: true  # equivalent to Kubernetes 'stdin: true'
    tty: true  # equivalent to Kubernetes 'tty: true'
    volumes:
      - /home2/jennyk0321/MASTER01/fedpod:/fedpod  # Absolute path on host mapped to /fedpod in container
      - /fedpod/cc359ppmi128:/fedpod/cc359ppmi128  # Absolute path on host mapped to /fedpod in container
      - /fedpod/states:/fedpod/states  # Absolute path on host mapped to /fedpod in container
      - /fedpod/logs:/fedpod/logs  # Absolute path on host mapped to /fedpod in container
      - /fedpod/runs:/fedpod/runs  # Absolute path on host mapped to /fedpod in container
