apiVersion: argoproj.io/v1alpha1
kind: Workflow                  
metadata:
  generateName: hello-world-   
spec:
  entrypoint: whalesay          
  serviceAccountName: argo-workflow-sa      # 이 줄을 추가해 주세요!
  templates:
    - name: whalesay              
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "hello world" ]
        resources: 
          limits:
            memory: 32Mi
            cpu: 100m
