apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fed-
spec:
  entrypoint: parallel-dag
  # onExit: infer-test-dag
  arguments:
    parameters:
    - name: data_root
      value: "data_cc359ppmicmc256_dwnusa"
    - name: data_set
      value: ""
    - name: train-script
      value: "run_train.sh"
    - name: agg-script
      value: "run_aggregation.sh"
    - name: infer-script
      value: "run_infer.sh"
    - name: forward-script
      value: "run_forward.sh"
    - name: rounds
      value: "20"
    - name: initial-round
      value: "00"
    - name: initial-epoch
      value: "000"
    - name: job-prefix
      value: "undefined"
    - name: split_csv
      value: "undefined" # "cc359ppmi128/CC359PPMI_nj4r12v3.csv"
    - name: init_model
      value: "None"
    - name: input_channel_names
      value: "None"
    - name: label_groups
      value: "None"
    - name: label_names
      value: "None"
    - name: label_index
      value: "None"
    - name: agg-algo
      value: "fedavg"
    - name: inst_01_ratio_0_4
      value: "100"
    - name: inst_02_ratio_0_4
      value: "100"
    - name: inst_03_ratio_0_4
      value: "100"
    - name: inst_04_ratio_0_4
      value: "100"
    - name: inst_05_ratio_0_4
      value: "100"
    - name: inst_06_ratio_0_4
      value: "100"
    - name: inst_07_ratio_0_4
      value: "100"
    - name: inst_08_ratio_0_4
      value: "100"
    - name: inst_09_ratio_0_4
      value: "100"
    - name: inst_10_ratio_0_4
      value: "100"
    - name: inst_11_ratio_0_4
      value: "100"
    - name: inst_12_ratio_0_4
      value: "100"
    - name: inst_13_ratio_0_4
      value: "100"
    - name: inst_14_ratio_0_4
      value: "100"
    - name: inst_15_ratio_0_4
      value: "100"
    - name: inst_16_ratio_0_4
      value: "100"
    - name: inst_17_ratio_0_4
      value: "100"
    - name: inst_18_ratio_0_4
      value: "100"
    - name: inst_19_ratio_0_4
      value: "100"
    - name: inst_20_ratio_0_4
      value: "100"
    - name: inst_21_ratio_0_4
      value: "100"
    - name: inst_22_ratio_0_4
      value: "100"
    - name: inst_23_ratio_0_4
      value: "100"
    - name: inst_01_ratio_5_9
      value: "100"
    - name: inst_02_ratio_5_9
      value: "100"
    - name: inst_03_ratio_5_9
      value: "100"
    - name: inst_04_ratio_5_9
      value: "100"
    - name: inst_05_ratio_5_9
      value: "100"
    - name: inst_06_ratio_5_9
      value: "100"
    - name: inst_07_ratio_5_9
      value: "100"
    - name: inst_08_ratio_5_9
      value: "100"
    - name: inst_09_ratio_5_9
      value: "100"
    - name: inst_10_ratio_5_9
      value: "100"
    - name: inst_11_ratio_5_9
      value: "100"
    - name: inst_12_ratio_5_9
      value: "100"
    - name: inst_13_ratio_5_9
      value: "100"
    - name: inst_14_ratio_5_9
      value: "100"
    - name: inst_15_ratio_5_9
      value: "100"
    - name: inst_16_ratio_5_9
      value: "100"
    - name: inst_17_ratio_5_9
      value: "100"
    - name: inst_18_ratio_5_9
      value: "100"
    - name: inst_19_ratio_5_9
      value: "100"
    - name: inst_20_ratio_5_9
      value: "100"
    - name: inst_21_ratio_5_9
      value: "100"
    - name: inst_22_ratio_5_9
      value: "100"
    - name: inst_23_ratio_5_9
      value: "100"
    - name: inst_01_ratio_10_14
      value: "100"
    - name: inst_02_ratio_10_14
      value: "100"
    - name: inst_03_ratio_10_14
      value: "100"
    - name: inst_04_ratio_10_14
      value: "100"
    - name: inst_05_ratio_10_14
      value: "100"
    - name: inst_06_ratio_10_14
      value: "100"
    - name: inst_07_ratio_10_14
      value: "100"
    - name: inst_08_ratio_10_14
      value: "100"
    - name: inst_09_ratio_10_14
      value: "100"
    - name: inst_10_ratio_10_14
      value: "100"
    - name: inst_11_ratio_10_14
      value: "100"
    - name: inst_12_ratio_10_14
      value: "100"
    - name: inst_13_ratio_10_14
      value: "100"
    - name: inst_14_ratio_10_14
      value: "100"
    - name: inst_15_ratio_10_14
      value: "100"
    - name: inst_16_ratio_10_14
      value: "100"
    - name: inst_17_ratio_10_14
      value: "100"
    - name: inst_18_ratio_10_14
      value: "100"
    - name: inst_19_ratio_10_14
      value: "100"
    - name: inst_20_ratio_10_14
      value: "100"
    - name: inst_21_ratio_10_14
      value: "100"
    - name: inst_22_ratio_10_14
      value: "100"
    - name: inst_23_ratio_10_14
      value: "100"
    - name: inst_01_ratio_15_19
      value: "100"
    - name: inst_02_ratio_15_19
      value: "100"
    - name: inst_03_ratio_15_19
      value: "100"
    - name: inst_04_ratio_15_19
      value: "100"
    - name: inst_05_ratio_15_19
      value: "100"
    - name: inst_06_ratio_15_19
      value: "100"
    - name: inst_07_ratio_15_19
      value: "100"
    - name: inst_08_ratio_15_19
      value: "100"
    - name: inst_09_ratio_15_19
      value: "100"
    - name: inst_10_ratio_15_19
      value: "100"
    - name: inst_11_ratio_15_19
      value: "100"
    - name: inst_12_ratio_15_19
      value: "100"
    - name: inst_13_ratio_15_19
      value: "100"
    - name: inst_14_ratio_15_19
      value: "100"
    - name: inst_15_ratio_15_19
      value: "100"
    - name: inst_16_ratio_15_19
      value: "100"
    - name: inst_17_ratio_15_19
      value: "100"
    - name: inst_18_ratio_15_19
      value: "100"
    - name: inst_19_ratio_15_19
      value: "100"
    - name: inst_20_ratio_15_19
      value: "100"
    - name: inst_21_ratio_15_19
      value: "100"
    - name: inst_22_ratio_15_19
      value: "100"
    - name: inst_23_ratio_15_19
      value: "100"
  templates:
  - name: parallel-dag
    dag:
      tasks:

      # # Round 18
      # # run_infer-train at Round 18
      # - name: infer-train-18
      #   template: infer-job
      #   arguments:
      #     parameters:
      #     - name: run-script
      #       value: "{{workflow.parameters.infer-script}}"
      #     - name: job-name
      #       value: "{{workflow.parameters.job-prefix}}_{{item.inst}}"
      #     - name: rounds
      #       value: "{{workflow.parameters.rounds}}"
      #     - name: round
      #       value: "{{tasks.agg-17.outputs.parameters.next-round}}"
      #     - name: epoch
      #       value: "000"
      #     - name: inst-id
      #       value: "{{item.inst}}"
      #     - name: split_csv
      #       value: "{{item.split_csv}}"
      #     - name: model_pth
      #       value: "/fedpod/states/{{workflow.parameters.job-prefix}}_0/R{{workflow.parameters.rounds}}r{{tasks.agg-17.outputs.parameters.next-round}}/models/R{{workflow.parameters.rounds}}r{{tasks.agg-17.outputs.parameters.next-round}}_agg.pth"
      #     - name: data_root
      #       value: "{{workflow.parameters.data_root}}"
      #     - name: data_set
      #       value: "{{workflow.parameters.data_set}}"
      #     - name: inst_root
      #       value: "inst_*"
      #     - name: input_channels
      #       value: "{{workflow.parameters.input_channel_names}}"
      #     - name: label_groups
      #       value: "{{workflow.parameters.label_groups}}"
      #     - name: label_names
      #       value: "{{workflow.parameters.label_names}}"
      #     - name: label_index
      #       value: "{{workflow.parameters.label_index}}"
      #     - name: seg_postfix
      #       value: "{{workflow.parameters.seg_postfix}}"
      #     - name: sel_list
      #       value: "[train]"
      #     - name: data_percentage
      #       value: "100"
      #   withItems:
      #   - { seed: "12001", inst:  "1", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12002", inst:  "2", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12003", inst:  "3", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12004", inst:  "4", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12005", inst:  "5", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12006", inst:  "6", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12007", inst:  "7", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12008", inst:  "8", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12009", inst:  "9", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12010", inst: "10", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12011", inst: "11", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12012", inst: "12", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12013", inst: "13", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12014", inst: "14", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12015", inst: "15", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12016", inst: "16", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12017", inst: "17", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12018", inst: "18", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12019", inst: "19", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12020", inst: "20", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12021", inst: "21", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12022", inst: "22", split_csv: "{{workflow.parameters.split_csv}}"}
      #   - { seed: "12023", inst: "23", split_csv: "{{workflow.parameters.split_csv}}"}
      #   # dependencies: [agg-17]

  # Round 20 (Forward)
  - name: infer-test-dag
    dag:
      tasks:
      - name: infer-20
        template: infer-job
        arguments:
          parameters:
          - name: run-script
            value: "{{workflow.parameters.forward-script}}"
          - name: job-name
            value: "{{workflow.parameters.job-prefix}}_{{item.inst}}_test"
          - name: rounds
            value: "20" # "{{item.rounds}}"
          - name: round
            value: "20" # "{{item.round}}"
          - name: epoch
            value: "000" # "{{item.epoch}}"
          - name: inst-id
            value: "{{item.inst}}"
          - name: split_csv
            value: "{{item.split_csv}}"
          - name: model_pth
            value: "{{item.model_pth}}"
          - name: data_root
            value: "{{workflow.parameters.data_root}}"
          - name: data_set
            value: "{{workflow.parameters.data_set}}"
          - name: inst_root
            value: "inst_00"
          - name: input_channels
            value: "{{workflow.parameters.input_channel_names}}"
          - name: label_groups
            value: "{{workflow.parameters.label_groups}}"
          - name: label_names
            value: "{{workflow.parameters.label_names}}"
          - name: label_index
            value: "{{workflow.parameters.label_index}}"
          - name: seg_postfix
            value: "{{workflow.parameters.seg_postfix}}"
          - name: sel_list
            value: "[test]"
        withItems:
        - { rounds: "{{workflow.parameters.rounds}}", 
            round: "20", 
            epoch: "000", 
            inst: "0", 
            split_csv: "{{workflow.parameters.split_csv}}", 
            model_pth: "/fedpod/states/{{workflow.parameters.job-prefix}}_0/R20r20/models/R20r20_agg.pth"}

  - name: train-job
    inputs:
      parameters:
      - name: job-name
      - name: seed
      - name: split_csv
      - name: train-script
      - name: round
      - name: epochs
      - name: epoch
      - name: inst-id
      - name: model_pth
      - name: data_percentage
    container:
      image: dwnusa/fedpod:v0.4.18.07
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      args:
        - >
          ./{{inputs.parameters.train-script}} 
          -S {{inputs.parameters.seed}} 
          -s 0
          -f 10
          -m [20,60]
          -g 0 
          -J {{inputs.parameters.job-name}} 
          -R {{workflow.parameters.rounds}} 
          -r {{inputs.parameters.round}} 
          -E {{inputs.parameters.epochs}} 
          -e {{inputs.parameters.epoch}} 
          -i {{inputs.parameters.inst-id}} 
          -c {{inputs.parameters.split_csv}} 
          -M {{inputs.parameters.model_pth}}
          -p {{inputs.parameters.data_percentage}}
          -D {{workflow.parameters.data_root}} 
          -d {{workflow.parameters.data_set}}
          -C {{workflow.parameters.input_channel_names}}
          -G {{workflow.parameters.label_groups}}
          -N {{workflow.parameters.label_names}}
          -I {{workflow.parameters.label_index}}
      resources:
        requests:
          cpu: "2"
          memory: "8G"
      volumeMounts:
      - name: csv-volume
        mountPath: /fedpod/experiments
      - name: cc359ppmi128-volume
        mountPath: /fedpod/data
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      - name: runs-volume
        mountPath: /fedpod/runs
      stdin: true
      tty: true
    volumes:
    - name: csv-volume
      hostPath:
        path: /fedpod/experiments  # 로컬 경로
        type: Directory
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/{{workflow.parameters.data_root}}  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory
    - name: runs-volume
      hostPath:
        path: /fedpod/runs  # 로컬 경로
        type: Directory


  - name: aggregation-job
    inputs:
      parameters:
      - name: agg-script
      - name: round
      - name: epochs
      - name: epoch
      - name: algorithm
      - name: inst-id
      - name: model_pth
    container:
      image: dwnusa/fedpod:v0.4.18.07
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      args: 
        - >
          ./{{inputs.parameters.agg-script}} 
          -R {{workflow.parameters.rounds}} 
          -r {{inputs.parameters.round}} 
          -E {{inputs.parameters.epochs}} 
          -e {{inputs.parameters.epoch}} 
          -j {{workflow.parameters.job-prefix}} 
          -i {{inputs.parameters.inst-id}} 
          -a {{inputs.parameters.algorithm}} 
          -M {{inputs.parameters.model_pth}}
      resources:
        requests:
          cpu: "2"
          memory: "4G"
      volumeMounts:
      - name: csv-volume
        mountPath: /fedpod/experiments
      - name: cc359ppmi128-volume
        mountPath: /fedpod/data
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      - name: runs-volume
        mountPath: /fedpod/runs
      stdin: true
      tty: true
    outputs:
      parameters:
      - name: next-round
        valueFrom:
          path: /tmp/next_round.txt  # Return the value from the temp file
          default: "{{workflow.parameters.rounds}}"
      - name: next-epoch
        valueFrom:
          path: /tmp/next_epoch.txt
          default: "0"
    volumes:
    - name: csv-volume
      hostPath:
        path: /fedpod/experiments  # 로컬 경로
        type: Directory
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/{{workflow.parameters.data_root}}  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory
    - name: runs-volume
      hostPath:
        path: /fedpod/runs  # 로컬 경로
        type: Directory

        
  - name: infer-job
    inputs:
      parameters:
      - name: run-script
      - name: job-name
      - name: rounds
      - name: round
      - name: epoch
      - name: inst-id
      - name: split_csv
      - name: model_pth
      - name: data_root
      - name: data_set
      - name: inst_root
      - name: input_channels
      - name: label_groups
      - name: label_names
      - name: label_index
      - name: seg_postfix
      - name: sel_list
    container:
      image: dwnusa/fedpod:v0.4.18.07
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      args: 
        - >
          ./{{inputs.parameters.run-script}}
          -s 1
          -g 0
          -J {{inputs.parameters.job-name}}
          -i {{inputs.parameters.inst-id}}
          -R {{inputs.parameters.rounds}}
          -r {{inputs.parameters.round}}
          -e {{inputs.parameters.epoch}}
          -c {{inputs.parameters.split_csv}}
          -M {{inputs.parameters.model_pth}}
          -t {{inputs.parameters.sel_list}}
          -D {{inputs.parameters.data_root}}
          -d {{inputs.parameters.data_set}}
          -n {{inputs.parameters.inst_root}}
          -C {{inputs.parameters.input_channels}}
          -G {{inputs.parameters.label_groups}}
          -N {{inputs.parameters.label_names}}
          -I {{inputs.parameters.label_index}}
          -p {{inputs.parameters.seg_postfix}}
      resources:
        requests:
          cpu: "2"
          memory: "8G"
      volumeMounts:
      - name: csv-volume
        mountPath: /fedpod/experiments
      - name: cc359ppmi128-volume
        mountPath: /fedpod/data
      - name: states-volume
        mountPath: /fedpod/states
      - name: logs-volume
        mountPath: /fedpod/logs
      - name: runs-volume
        mountPath: /fedpod/runs
      stdin: true
      tty: true
    volumes:
    - name: csv-volume
      hostPath:
        path: /fedpod/experiments  # 로컬 경로
        type: Directory
    - name: cc359ppmi128-volume
      hostPath:
        path: /fedpod/{{inputs.parameters.data_root}}  # 로컬 경로
        type: Directory
    - name: states-volume
      hostPath:
        path: /fedpod/states  # 로컬 경로
        type: Directory
    - name: logs-volume
      hostPath:
        path: /fedpod/logs  # 로컬 경로
        type: Directory
    - name: runs-volume
      hostPath:
        path: /fedpod/runs  # 로컬 경로
        type: Directory

  - name: dummy-task
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["echo '12' > /tmp/next_round.txt; echo '0' > /tmp/next_epoch.txt"]
    outputs:
      parameters:
      - name: next-round
        valueFrom:
          path: /tmp/next_round.txt
      - name: next-epoch
        valueFrom:
          path: /tmp/next_epoch.txt