version: '3'
services:
  run_train_fets:
    image: dwnusa/fedpod:v0.4.17-test-cuda
    container_name: run_train_fets
    command: >
      /bin/bash -c "/fedpod/run_train_fets.sh 
      -S ${SEED}
      -s 1 
      -f 5
      -m [10,20,25]
      -g 1 
      -J ${JOBNAME}
      -R ${ROUNDS}
      -r ${ROUND}
      -E ${EPOCHS}
      -e ${EPOCH}
      -i ${INSTID}
      -c ${SPLIT_CSV}
      -M ${MODEL}
      -p 100
      -D ${DATAROOT}
      -d ${DATASET}
      -C ${INPUT_CHANNEL_NAMES}
      -G ${LABEL_GROUPS}
      -N ${LABEL_NAMES}
      -I ${LABEL_INDEX}"
    stdin_open: true
    tty: true
    volumes:
      - /home/cmc_admin/workspace/fedpod:/fedpod
      - /home/cmc_admin/workspace/fedpod/${DATAROOT}:/fedpod/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  run_agg_fets:
    image: dwnusa/fedpod:v0.4.17-test-cuda
    container_name: run_agg_fets
    command: >
      /bin/bash -c "/fedpod/run_aggregation.sh 
      -R ${ROUNDS}
      -r ${ROUND}
      -E ${EPOCHS}
      -e ${EPOCH}
      -j ${JOBPREFIX}
      -i ${INSTID}
      -a ${ALGO}
      -M {{inputs.parameters.model_pth}}"
    stdin_open: true
    tty: true
    volumes:
      - /home/cmc_admin/workspace/fedpod:/fedpod
      - /home/cmc_admin/workspace/fedpod/${DATAROOT}:/fedpod/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]





  run_train_cc359:
    image: dwnusa/fedpod:v0.4.17-test-cuda
    container_name: run_train_cc359
    command: >
      /bin/bash -c "/fedpod/run_train_cc359.sh 
      -S {SEED}
      -s 1 
      -f 5
      -m [10,20,25]
      -g 1 
      -J ${JOBNAME}
      -R ${ROUNDS}
      -r ${ROUND}
      -E 30
      -e 0
      -i ${INSTID}
      -c ${SPLIT_CSV}
      -M ${MODEL}
      -p 100
      -D ${DATAROOT}
      -d ${DATASET}
      -C ${INPUT_CHANNEL_NAMES}
      -G ${LABEL_GROUPS}
      -N ${LABEL_NAMES}
      -I ${LABEL_INDEX}"
    stdin_open: true
    tty: true
    volumes:
      - /home/cmc_admin/workspace/fedpod:/fedpod
      - /home/cmc_admin/workspace/fedpod/${DATAROOT}:/fedpod/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
